
-record('Communication', {anyAttribs :: anyAttribs(),
	id :: id() | undefined,
	meta :: 'Meta'() | undefined,
	implicitRules :: uri() | undefined,
	language :: code() | undefined,
	text :: 'Narrative'() | undefined,
	contained :: ['ResourceContainer'()] | undefined,
	extension :: ['Extension'()] | undefined,
	modifierExtension :: ['Extension'()] | undefined,
	identifier :: ['Identifier'()] | undefined,
	instantiatesCanonical :: [canonical()] | undefined,
	instantiatesUri :: [uri()] | undefined,
	basedOn :: ['Reference'()] | undefined,
	partOf :: ['Reference'()] | undefined,
	inResponseTo :: ['Reference'()] | undefined,
	status :: 'EventStatus'(),
	statusReason :: 'CodeableConcept'() | undefined,
	category :: ['CodeableConcept'()] | undefined,
	priority :: 'RequestPriority'() | undefined,
	medium :: ['CodeableConcept'()] | undefined,
	subject :: 'Reference'() | undefined,
	topic :: 'CodeableConcept'() | undefined,
	about :: ['Reference'()] | undefined,
	encounter :: 'Reference'() | undefined,
	sent :: dateTime() | undefined,
	received :: dateTime() | undefined,
	recipient :: ['Reference'()] | undefined,
	sender :: 'Reference'() | undefined,
	reasonCode :: ['CodeableConcept'()] | undefined,
	reasonReference :: ['Reference'()] | undefined,
	payload :: ['Communication.Payload'()] | undefined,
	note :: ['Annotation'()] | undefined}).
-type 'Communication'() :: #'Communication'{}.

