-record('ServiceRequest', {anyAttribs :: anyAttribs(),
	id :: id() | undefined,
	meta :: 'Meta'() | undefined,
	implicitRules :: uri() | undefined,
	language :: code() | undefined,
	text :: 'Narrative'() | undefined,
	contained :: ['ResourceContainer'()] | undefined,
	extension :: ['Extension'()] | undefined,
	modifierExtension :: ['Extension'()] | undefined,
	identifier :: ['Identifier'()] | undefined,
	instantiatesCanonical :: [canonical()] | undefined,
	instantiatesUri :: [uri()] | undefined,
	basedOn :: ['Reference'()] | undefined,
	replaces :: ['Reference'()] | undefined,
	requisition :: 'Identifier'() | undefined,
	status :: 'RequestStatus'(),
	intent :: 'RequestIntent'(),
	category :: ['CodeableConcept'()] | undefined,
	priority :: 'RequestPriority'() | undefined,
	doNotPerform :: boolean() | undefined,
	code :: 'CodeableConcept'() | undefined,
	orderDetail :: ['CodeableConcept'()] | undefined,
	choice :: 'Ratio'() | 'Range'() | 'Quantity'() | 'Duration'() | 'Age'() | 'Distance'() | 'Count'() | undefined,
	subject :: 'Reference'(),
	encounter :: 'Reference'() | undefined,
	choice1 :: 'Timing'() | 'Period'() | dateTime() | undefined,
	choice2 :: 'CodeableConcept'() | boolean() | undefined,
	authoredOn :: dateTime() | undefined,
	requester :: 'Reference'() | undefined,
	performerType :: 'CodeableConcept'() | undefined,
	performer :: ['Reference'()] | undefined,
	locationCode :: ['CodeableConcept'()] | undefined,
	locationReference :: ['Reference'()] | undefined,
	reasonCode :: ['CodeableConcept'()] | undefined,
	reasonReference :: ['Reference'()] | undefined,
	insurance :: ['Reference'()] | undefined,
	supportingInfo :: ['Reference'()] | undefined,
	specimen :: ['Reference'()] | undefined,
	bodySite :: ['CodeableConcept'()] | undefined,
	note :: ['Annotation'()] | undefined,
	patientInstruction :: string() | undefined,
	relevantHistory :: ['Reference'()] | undefined}).

-type 'ServiceRequest'() :: #'ServiceRequest'{}.


